// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKwwl755PKUaKKTTRmPA4fN-IzfIFhj8',
    appId: '1:588024868184:web:8224637769f2708bf4492d',
    messagingSenderId: '588024868184',
    projectId: 'fridge-pantry-dj-6aa3f',
    authDomain: 'fridge-pantry-dj-6aa3f.firebaseapp.com',
    databaseURL: 'https://fridge-pantry-dj-6aa3f-default-rtdb.firebaseio.com',
    storageBucket: 'fridge-pantry-dj-6aa3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdNGJQpCK_1cvyUpF-UF_VYXpe9VUQI0',
    appId: '1:588024868184:android:6c4576c8fb626a5af4492d',
    messagingSenderId: '588024868184',
    projectId: 'fridge-pantry-dj-6aa3f',
    databaseURL: 'https://fridge-pantry-dj-6aa3f-default-rtdb.firebaseio.com',
    storageBucket: 'fridge-pantry-dj-6aa3f.firebasestorage.app',
  );
}
